// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/atomix/dazl (interfaces: Writer)

// Package dazl is a generated GoMock package.
package dazl

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockWriter) Debug(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", arg0)
}

// Debug indicates an expected call of Debug.
func (mr *MockWriterMockRecorder) Debug(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockWriter)(nil).Debug), arg0)
}

// Error mocks base method.
func (m *MockWriter) Error(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", arg0)
}

// Error indicates an expected call of Error.
func (mr *MockWriterMockRecorder) Error(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockWriter)(nil).Error), arg0)
}

// Fatal mocks base method.
func (m *MockWriter) Fatal(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fatal", arg0)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockWriterMockRecorder) Fatal(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockWriter)(nil).Fatal), arg0)
}

// Info mocks base method.
func (m *MockWriter) Info(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", arg0)
}

// Info indicates an expected call of Info.
func (mr *MockWriterMockRecorder) Info(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockWriter)(nil).Info), arg0)
}

// Panic mocks base method.
func (m *MockWriter) Panic(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Panic", arg0)
}

// Panic indicates an expected call of Panic.
func (mr *MockWriterMockRecorder) Panic(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Panic", reflect.TypeOf((*MockWriter)(nil).Panic), arg0)
}

// Warn mocks base method.
func (m *MockWriter) Warn(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", arg0)
}

// Warn indicates an expected call of Warn.
func (mr *MockWriterMockRecorder) Warn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockWriter)(nil).Warn), arg0)
}

// WithName mocks base method.
func (m *MockWriter) WithName(arg0 string) Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithName", arg0)
	ret0, _ := ret[0].(Writer)
	return ret0
}

// WithName indicates an expected call of WithName.
func (mr *MockWriterMockRecorder) WithName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithName", reflect.TypeOf((*MockWriter)(nil).WithName), arg0)
}

// WithMessageKey mocks base method.
func (m *MockWriter) WithMessageKey(arg0 string) Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithMessageKey", arg0)
	ret0, _ := ret[0].(Writer)
	return ret0
}

// WithMessageKey indicates an expected call of WithMessageKey.
func (mr *MockWriterMockRecorder) WithMessageKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithMessageKey", reflect.TypeOf((*MockWriter)(nil).WithMessageKey), arg0)
}

// WithNameEnabled mocks base method.
func (m *MockWriter) WithNameEnabled() (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithNameEnabled")
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithNameEnabled indicates an expected call of WithNameEnabled.
func (mr *MockWriterMockRecorder) WithNameEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithNameEnabled", reflect.TypeOf((*MockWriter)(nil).WithNameEnabled))
}

// WithNameKey mocks base method.
func (m *MockWriter) WithNameKey(arg0 string) (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithNameKey", arg0)
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithNameKey indicates an expected call of WithNameKey.
func (mr *MockWriterMockRecorder) WithNameKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithNameKey", reflect.TypeOf((*MockWriter)(nil).WithNameKey), arg0)
}

// WithLevelEnabled mocks base method.
func (m *MockWriter) WithLevelEnabled() (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithLevelEnabled")
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithLevelEnabled indicates an expected call of WithLevelEnabled.
func (mr *MockWriterMockRecorder) WithLevelEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithLevelEnabled", reflect.TypeOf((*MockWriter)(nil).WithLevelEnabled))
}

// WithLevelKey mocks base method.
func (m *MockWriter) WithLevelKey(arg0 string) (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithLevelKey", arg0)
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithLevelKey indicates an expected call of WithLevelKey.
func (mr *MockWriterMockRecorder) WithLevelKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithLevelKey", reflect.TypeOf((*MockWriter)(nil).WithLevelKey), arg0)
}

// WithLevelFormat mocks base method.
func (m *MockWriter) WithLevelFormat(arg0 LevelFormat) (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithLevelFormat", arg0)
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithLevelFormat indicates an expected call of WithLevelFormat.
func (mr *MockWriterMockRecorder) WithLevelFormat(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithLevelFormat", reflect.TypeOf((*MockWriter)(nil).WithLevelFormat), arg0)
}

// WithTimestampEnabled mocks base method.
func (m *MockWriter) WithTimestampEnabled() (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimestampEnabled")
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithTimestampEnabled indicates an expected call of WithTimestampEnabled.
func (mr *MockWriterMockRecorder) WithTimestampEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimestampEnabled", reflect.TypeOf((*MockWriter)(nil).WithTimestampEnabled))
}

// WithTimestampKey mocks base method.
func (m *MockWriter) WithTimestampKey(arg0 string) (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimestampKey", arg0)
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithTimestampKey indicates an expected call of WithTimestampKey.
func (mr *MockWriterMockRecorder) WithTimestampKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimestampKey", reflect.TypeOf((*MockWriter)(nil).WithTimestampKey), arg0)
}

// WithTimestampFormat mocks base method.
func (m *MockWriter) WithTimestampFormat(arg0 TimestampFormat) (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimestampFormat", arg0)
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithTimestampFormat indicates an expected call of WithTimestampFormat.
func (mr *MockWriterMockRecorder) WithTimestampFormat(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimestampFormat", reflect.TypeOf((*MockWriter)(nil).WithTimestampFormat), arg0)
}

// WithCallerEnabled mocks base method.
func (m *MockWriter) WithCallerEnabled() (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCallerEnabled")
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithCallerEnabled indicates an expected call of WithCallerEnabled.
func (mr *MockWriterMockRecorder) WithCallerEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCallerEnabled", reflect.TypeOf((*MockWriter)(nil).WithCallerEnabled))
}

// WithCallerKey mocks base method.
func (m *MockWriter) WithCallerKey(arg0 string) (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCallerKey", arg0)
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithCallerKey indicates an expected call of WithCallerKey.
func (mr *MockWriterMockRecorder) WithCallerKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCallerKey", reflect.TypeOf((*MockWriter)(nil).WithCallerKey), arg0)
}

// WithCallerFormat mocks base method.
func (m *MockWriter) WithCallerFormat(arg0 CallerFormat) (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCallerFormat", arg0)
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithCallerFormat indicates an expected call of WithCallerFormat.
func (mr *MockWriterMockRecorder) WithCallerFormat(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCallerFormat", reflect.TypeOf((*MockWriter)(nil).WithCallerFormat), arg0)
}

// WithStacktraceEnabled mocks base method.
func (m *MockWriter) WithStacktraceEnabled() (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStacktraceEnabled")
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithStacktraceEnabled indicates an expected call of WithStacktraceEnabled.
func (mr *MockWriterMockRecorder) WithStacktraceEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStacktraceEnabled", reflect.TypeOf((*MockWriter)(nil).WithStacktraceEnabled))
}

// WithStacktraceKey mocks base method.
func (m *MockWriter) WithStacktraceKey(arg0 string) (Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStacktraceKey", arg0)
	ret0, _ := ret[0].(Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithStacktraceKey indicates an expected call of WithStacktraceKey.
func (mr *MockWriterMockRecorder) WithStacktraceKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStacktraceKey", reflect.TypeOf((*MockWriter)(nil).WithStacktraceKey), arg0)
}
