# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

encoders:
  json:
    fields:
      - message:
          key: message
      - level:
          format: uppercase
      - caller:
          format: short
      - timestamp:
          format: iso8601

writers:
  stdout:
    encoder: json

rootLogger:
  level: info
  outputs:
    - stdout
