# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Run tests

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic

      - name: Run zap tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
        working-directory: zap

      - name: Run zerolog tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
        working-directory: zerolog

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        files: ./coverage.txt,zap/coverage.txt,zerolog/coverage.txt
